services:
  # Listing Database service
  listing-db:
    image: mysql:8.0
    container_name: listing_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: listing_db
    ports:
      - "3306:3306"
    volumes:
      - listing_mysql_data:/var/lib/mysql
      - ./listing_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - organ_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Bidding Database service
  bidding-db:
    image: mysql:8.0
    container_name: bidding_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: bidding_db
    ports:
      - "3307:3306"  # Changed port to avoid conflict
    volumes:
      - bidding_mysql_data:/var/lib/mysql
      - ./bidding_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - organ_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Listing Microservice
  list-service:
    build: ./list-service
    container_name: list_service
    restart: always
    depends_on:
      - listing-db
    environment:
      # DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@listing-db:3306/listing_db
      DB_HOST: listing-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      DB_NAME: listing_db
      NODE_ENV: ${NODE_ENV:-development}
      LISTING_SERVICE_URL: http://list-service:3001
      RESOLUTION_INTERVAL_MINUTES: 5
    ports:
      - "3001:3001"
    networks:
      - organ_network
    volumes:
      - ./list-service:/app
      - /app/node_modules


  # Bidding Microservice
  bid-service:
    build: ./bid-service
    container_name: bid_service
    restart: always
    depends_on:
      - bidding-db
    environment:
      # DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@bidding-db:3306/bidding_db
      DB_HOST: bidding-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: bidding_db
      NODE_ENV: ${NODE_ENV:-development}
      BIDDING_SERVICE_URL: http://bid-service:3002
      LISTING_SERVICE_URL: http://list-service:3001
    ports:
      - "3002:3002"
    networks:
      - organ_network
    volumes:
      - ./bid-service:/app
      - /app/node_modules


  # View Listing Bids Composite Microservice (Python)
  view-listing-bids-service:
    build: ./view-listing-bids-service
    container_name: view_listing_bids_service
    restart: always
    depends_on:
      - list-service
      - bid-service
    environment:
      LISTING_SERVICE_URL: http://list-service:3001
      BIDDING_SERVICE_URL: http://bid-service:3002
    ports:
      - "5001:5001"
    networks:
      - organ_network
    volumes:
      - ./view-listing-bids-service:/app

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"  # Kong proxy
      - "8001:8001"  # Kong admin
    networks:
      - organ_network

   # Frontend Application
  frontend:
    build: ./frontend-logic
    container_name: frontend
    restart: always
    depends_on:
      - view-listing-bids-service
    ports:
      - "3000:3000"  # Next.js default port
    networks:
      - organ_network
    volumes:
      - ./frontend-logic:/app
      - /app/node_modules
      - /app/.next
      
networks:
  organ_network:
    driver: bridge

volumes:
  listing_mysql_data:
  bidding_mysql_data: