version: '3.8'
services:
  orders-service:
    build: ./services/orders-service
    container_name: orders-service
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=mysql
      - DB_USER=orders_user
      - DB_PASS=orders_pass
      - DB_NAME=orders_db
      - USER_SERVICE_URL=http://user-service:3001/users
      - ORGANS_SERVICE_URL=http://organs-service:3002/organs
      - TRANSACTION_SERVICE_URL=http://transaction-service:3003/transactions
    depends_on:
      - mysql
      - user-service
      - organs-service
      - transaction-service

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "3001:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=user_user
      - DB_PASS=user_pass
      - DB_NAME=user_db
    depends_on:
      - mysql

  organs-service:
    build: ./services/organs-service
    container_name: organs-service
    ports:
      - "3002:5001"
    environment:
      - DB_HOST=mysql
      - DB_USER=organs_user
      - DB_PASS=organs_pass
      - DB_NAME=organs_db
    depends_on:
      - mysql

  transaction-service:
    build: ./services/transaction-service
    container_name: transaction-service
    ports:
      - "3003:3003"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - my-mysql-data:/var/lib/mysql

volumes:
  my-mysql-data: