services:
  # Listing Database service
  listing-db:
    image: mysql:8.0
    container_name: listing_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: listing_db
    ports:
      - "3306:3306"
    volumes:
      - listing_mysql_data:/var/lib/mysql
      - ./listing_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - organ_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Bidding Database service, comment out if want external
  bidding-db:
    image: mysql:8.0
    container_name: bidding_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bidding_db
    command: --port=3307  # Make MySQL listen on port 3307
    ports:
      - "3307:3307"
    volumes:
      - bidding_mysql_data:/var/lib/mysql
      - ./bidding_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - organ_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}", "--port=3307"]
      interval: 5s
      timeout: 5s
      retries: 5

  resolving-db:
    image: mysql:8.0
    container_name: resolving_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: resolving_db
    command: --port=3308  # Make MySQL listen on port 3308
    ports:
      - "3308:3308"
    volumes:
      - resolving_mysql_data:/var/lib/mysql
      - ./resolving_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - organ_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}", "--port=3308"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Listing Microservice
  list-service:
    build: ./list-service
    container_name: list_service
    restart: always
    depends_on:
      listing-db:
        condition: service_healthy
    environment:
      DB_HOST: listing-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: listing_db
      NODE_ENV: ${NODE_ENV:-development}
      LISTING_SERVICE_URL: ${LISTING_SERVICE_URL}
      RESOLUTION_INTERVAL_MINUTES: 5
      KAFKA_BROKERS: kafka:9092
      LISTING_EVENTS_TOPIC: listing-events
    ports:
      - "3001:3001"
    networks:
      - organ_network
    volumes:
      - ./list-service:/app
      - /app/node_modules

  # # Bidding Microservice comment out if want external
  bid-service:
    build: ./bid-service
    container_name: bid_service
    restart: always
    depends_on:
      bidding-db:
        condition: service_healthy
    environment:
      DB_HOST: bidding-db
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: bidding_db
      NODE_ENV: ${NODE_ENV:-development}
      BIDDING_SERVICE_URL: ${BIDDING_SERVICE_URL}
    ports:
      - "3002:3002"
    networks:
      - organ_network
    volumes:
      - ./bid-service:/app
      - /app/node_modules

  # Bidding Microservice
  resolve-service:
    build: ./resolve-service
    container_name: resolve_service
    restart: always
    depends_on:
      resolving-db:
        condition: service_healthy
    environment:
      DB_HOST: resolving-db
      DB_PORT: 3308
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: resolving_db
      NODE_ENV: ${NODE_ENV:-development}
      BIDDING_SERVICE_URL: ${BIDDING_SERVICE_URL}
      LISTING_SERVICE_URL: ${LISTING_SERVICE_URL}
    ports:
      - "3004:3004"
    networks:
      - organ_network
    volumes:
      - ./resolve-service:/app
      - /app/node_modules

  # View Listing Bids Composite Microservice (Python)
  view-listing-bids-service:
    build: ./view-listing-bids-service
    container_name: view_listing_bids_service
    restart: always
    depends_on:
      - list-service
    environment:
      LISTING_SERVICE_URL: ${LISTING_SERVICE_URL}
      BIDDING_SERVICE_URL: ${BIDDING_SERVICE_URL}
    ports:
      - "5001:5001"
    networks:
      - organ_network
    volumes:
      - ./view-listing-bids-service:/app

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"  # Kong proxy
      - "8001:8001"  # Kong admin
    networks:
      - organ_network
  # Frontend Application (HTML-based)
  frontend:
    build: ./frontend-html
    container_name: frontend
    restart: always
    depends_on:
      - view-listing-bids-service
      - list-service
      - kong
    ports:
      - "3000:3000"
    networks:
      - organ_network

  notification:
    build: ./notification
    container_name: notification
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - EMAIL_FROM=${EMAIL_FROM}
      - TEST_MODE=true
    volumes:
      - ./notification:/app
      - /app/node_modules
    networks:
      - organ_network
    restart: unless-stopped
    depends_on:
      - kafka

  # Kafka and Zookeeper services
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - organ_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "listing-events:1:1,notification-events:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - organ_network

networks:
  organ_network:
    driver: bridge

volumes:
  listing_mysql_data:
  bidding_mysql_data:
  resolving_mysql_data: