version: '3.8'
services:
  orders-service:
    build: ./services/orders-service
    container_name: orders-service
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=mysql
      - DB_USER=orders_user
      - DB_PASS=orders_pass
      - DB_NAME=orders_db
      - USER_SERVICE_URL=http://user-service:3001/users
      - ORGANS_SERVICE_URL=http://organs-service:3002/organs
      - TRANSACTION_SERVICE_URL=http://transaction-service:3003/transactions
    depends_on:
      - mysql
      - user-service
      - organs-service
      - transaction-service

  user-service:
    # ...
  
  organs-service:
    # ...
  
  transaction-service:
    # ...
  
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - my-mysql-data:/var/lib/mysql

volumes:
  my-mysql-data:
