services:
  # Listing Database service
  listing-db:
    image: postgres:13
    container_name: listing_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: listing_db
    ports:
      - "5432:5432"
    volumes:
      - listing_postgres_data:/var/lib/postgresql/data
      - ./listing_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - organ_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Bidding Database service
  bidding-db:
    image: postgres:13
    container_name: bidding_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: bidding_db
    ports:
      - "5433:5432"  # Changed port to avoid conflict
    volumes:
      - bidding_postgres_data:/var/lib/postgresql/data
      - ./bidding_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - organ_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Listing Microservice
  listing-service:
    build: ./listing-service
    container_name: listing_service
    restart: always
    depends_on:
      - listing-db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@listing-db:5432/${POSTGRES_DB:-listing_db}
      DB_HOST: listing-db
      POSTGRES_DB: listing_db
      NODE_ENV: ${NODE_ENV:-development}
      BIDDING_SERVICE_URL: http://bidding-service:3002
      RESOLUTION_INTERVAL_MINUTES: 5
    ports:
      - "3001:3001"
    networks:
      - organ_network
    volumes:
      - ./listing-service:/app
      - ./listing_db:/app/db
      - /app/node_modules

  # Bidding Microservice
  bidding-service:
    build: ./bidding-service
    container_name: bidding_service
    restart: always
    depends_on:
      - bidding-db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@bidding-db:5432/${POSTGRES_DB:-bidding_db}
      DB_HOST: bidding-db
      POSTGRES_DB: bidding_db
      NODE_ENV: ${NODE_ENV:-development}
      LISTING_SERVICE_URL: http://listing-service:3001
    ports:
      - "3002:3002"
    networks:
      - organ_network
    volumes:
      - ./bidding-service:/app
      - ./bidding_db:/app/db
      - /app/node_modules

  # View Listing Bids Composite Microservice (Python)
  view-listing-bids-service:
    build: ./view-listing-bids-service
    container_name: view_listing_bids_service
    restart: always
    depends_on:
      - listing-service
      - bidding-service
    environment:
      LISTING_SERVICE_URL: http://listing-service:3001
      BIDDING_SERVICE_URL: http://bidding-service:3002
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - organ_network
    volumes:
      - ./view-listing-bids-service:/app

   # Frontend Application
  frontend:
    build: ./frontend-logic
    container_name: frontend
    restart: always
    depends_on:
      - view-listing-bids-service
    ports:
      - "3000:3000"  # Next.js default port
    networks:
      - organ_network
    volumes:
      - ./frontend-logic:/app
      - /app/node_modules
      - /app/.next
      
networks:
  organ_network:
    driver: bridge

volumes:
  listing_postgres_data:
  bidding_postgres_data: